# in base install requirements
FROM python:3.14.6-alpine3.23 AS base
WORKDIR /var/app

RUN python3 -m venv /venv
ENV PATH="/venv/bin:$PATH"

RUN --mount=type=cache,target=/root/.cache/pip \
    --mount=type=bind,source=requirements.txt,target=requirements.txt \
    pip install -r requirements.txt


# in build copy over all build files
FROM python:3.14.6-alpine3.23 AS build

WORKDIR /var/app

COPY --from=base /venv /venv
ENV PATH="/venv/bin:$PATH"

COPY . .


# For development with uvicorn reload
FROM build AS dev

EXPOSE 8000

CMD ["/venv/bin/python3", "-m", "uvicorn", "--reload", "src.index:app", "--host=0.0.0.0", "--port=8000"]


# For prod without reload
FROM build AS bin

EXPOSE 8000

CMD ["/venv/bin/python3", "-m", "uvicorn", "src.index:app", "--host=0.0.0.0", "--port=8000"]